export const STYLE_ATTRIBUTE = 'jsx'
export const GLOBAL_ATTRIBUTE = 'global'
export const STYLE_COMPONENT_ID = 'styleId'
export const MARKUP_ATTRIBUTE = 'data-jsx'
export const MARKUP_ATTRIBUTE_EXTERNAL = 'data-jsx-ext'
export const STYLE_COMPONENT = '_JSXStyle'
export const STYLE_COMPONENT_CSS = 'css'
