name: CI

on:
  push:
    branches:
      - main
      - alpha
      - beta
    tags:
      - '!*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Enable pnpm
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          CI: true

      - name: Build
        run: pnpm build
        env:
          CI: true

      - name: Lint
        run: pnpm lint
        env:
          CI: true

      - name: Test
        run: pnpm test
        env:
          CI: true

      - name: Test types
        run: pnpm test-types
        env:
          CI: true

      - name: Release
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/alpha' || github.ref == 'refs/heads/beta')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
        run: pnpm semantic-release
